## Different perspective
1. PCA
2. manual
   - with and without trustLevel
3. automatic generation

## Code for test
prepare different input dataset and test at 10-fold stratified cross validation set
1. train_data (raw data)
2. X_train_norm_enc data (normalized and encode)
3. X_train_norm (normalized)

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
import matplotlib.pyplot as plt
%matplotlib inline
from classifiers import *
from sklearn.metrics import confusion_matrix

In [2]:
train_data = pd.read_csv('data/train.csv', sep = '|')
test_data = pd.read_csv('data/test.csv', sep = '|')
print(f'Train set has {train_data.shape[0]} entries and {train_data.shape[1]} features')
print(f'Test set has {test_data.shape[0]} entries and {test_data.shape[1]} features')

Train set has 1879 entries and 10 features
Test set has 498121 entries and 9 features


In [3]:
## normalize w/ encode 
y = train_data['fraud']
X = train_data.drop(columns=['fraud']).astype(float)
X_all = X.append(test_data, sort=False)
X_all= pd.get_dummies(X_all, columns=['trustLevel'], prefix='trustLevel')
X_norm_encode = pd.DataFrame(MinMaxScaler().fit_transform(X_all), columns=X_all.columns, index=X_all.index)
print(X_norm_encode.shape)
X_train_norm_enc = X_norm_encode.iloc[:1879,:]
X_test_norm_enc = X_norm_encode.iloc[1879:,:]
# print(X_train_norm_enc)

(500000, 14)


/usr/local/lib/python3.7/site-packages/sklearn/preprocessing/data.py:323: DataConversionWarning: Data with input dtype uint8, float64 were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)


In [4]:
## normalized w/o encode 
y = train_data['fraud']
X = train_data.drop(columns=['fraud']).astype(float)
X_all = X.append(test_data, sort=False)
X_norm = pd.DataFrame(MinMaxScaler().fit_transform(X_all), columns=X_all.columns, index=X_all.index)
print(X_norm.shape)
X_train_norm = X_norm.iloc[:1879,:]
X_test_norm = X_norm.iloc[1879:,:]
# print(X_train_norm)

(500000, 9)


In [5]:
def code_for_test(X,y):
    """
    test code with 10-fold stratified cross validation
    parameters
    X: trainset features after generation
    y: trainset y label
    """
    evaluate_classification(X, y)

In [6]:
code_for_test(X_train_norm_enc, y)

[-55 -55 -55 -55 -50 -50 -50 -50 -50 -50]
Linear SVM: test core = -520 
[ -55  -55  -55  -80  -50  -50  -40  -75 -100  -50]
RBF SVM: test core = -610 
[ -55  -35  -60 -110  -40  -40  -55  -70  -90  -75]
Logistic Regression: test core = -630 
[-55 -45 -55 -35 -50 -50 -40 -75 -50 -50]
Neural Net: test core = -505 
[-55 -55 -55 -45 -50 -50 -40 -50 -50 -50]
Random Forest: test core = -520 
[ 35 -65 -15  25  -5 -35  10   5 -30  20]
AdaBoost: test core = -55 
[  0  10 -25   0 -20 -20 -15  15 -15  10]
XGBoost: test core = -60 
